formsapp/urls.py
from django.urls import path
from .views import forms_list_view, form_detail_view, form_edit_view, user_leads_view
from .views import user_form_detail_view, user_form_edit_view, status_change_not_allowed_view
from usersapp.views import unauthorized_view

urlpatterns = [
    path('list/', forms_list_view, name='forms_list'),
    path('detail/<int:submission_id>/', form_detail_view, name='form_detail'),
    path('edit/<int:submission_id>/', form_edit_view, name='form_edit'),
    path('unauthorized/', unauthorized_view , name='unauthorized'),
    path('my_leads/', user_leads_view, name='user_leads'),
    path('user_form_detail/<int:submission_id>/', user_form_detail_view, name='user_form_detail'),
    path('user_form_edit/<int:submission_id>/', user_form_edit_view, name='user_form_edit'),
    path('status-change-not-allowed/', status_change_not_allowed_view, name='status_change_not_allowed'),
]

leadsmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingapp.urls')),
    path('users/', include('usersapp.urls')),
    path('forms/', include('formsapp.urls')),
]

formsapp/models.py
from django.db import models
from usersapp.models import CustomUser
from django.contrib.auth import get_user_model

ESTADO_CHOICES = [
    ('pendiente', 'Pendiente'),
    ('asignado', 'Asignado'),
    ('contactado', 'Contactado'),
    ('faltaCotizar', 'Falta cotizar'),
    ('cotizado', 'Cotizado'),
    ('interezadoAvanzar', 'Interesados en avanzar'),
    ('gestionExitosa', 'Gestion exitosa'),
    ('pospuesto', 'pospuesto'),
    ('noAvanzo', 'No avanzo'),
    ('noViable', 'No viable'),
    ('nuevoCliente', 'Nuevo cliente'),
    ('negativo', 'Negativo'),
]

class Campaign(models.Model):
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class FormSubmission(models.Model):

    empresa = models.CharField(max_length=255)
    fecha_creacion = models.DateTimeField()
    razon_social = models.CharField(max_length=255, blank=True, null=True)
    nombre_y_apellido = models.CharField(max_length=255, blank=True, null=True)
    servicio = models.CharField(max_length=255, blank=True, null=True)
    mail = models.EmailField(blank=True, null=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    origen = models.CharField(max_length=255)
    sub_origen = models.CharField(max_length=255)
    mensaje = models.TextField(blank=True, null=True)
    avance = models.CharField(max_length=50)
    estado = models.CharField(max_length=50, choices=ESTADO_CHOICES)
    form_id = models.IntegerField()
    submission_id = models.IntegerField(unique=True)
    data = models.JSONField()  # Store the raw JSON data
    assigned_user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_user')
    management_message = models.TextField(null=True, blank=True)
    campaign = models.ForeignKey('Campaign', on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Extract the user from kwargs

        if self.pk:
            old_instance = FormSubmission.objects.get(pk=self.pk)
            if old_instance.estado != self.estado:
                LeadHistory.objects.create(
                    form_submission=self,
                    previous_status=old_instance.estado,
                    new_status=self.estado,
                    updated_by=user  # Use the passed user
                )
        else:
            LeadHistory.objects.create(
                form_submission=self,
                previous_status=None,
                new_status=self.estado,
                updated_by=user  # Use the passed user
            )
        super(FormSubmission, self).save(*args, **kwargs)

    # def is_status_change_allowed(self, new_status, user):
    #     # Get the current and new status hierarchy levels
    #     current_status_hierarchy = dict((status[0], status[2]) for status in ESTADO_CHOICES).get(self.estado)
    #     new_status_hierarchy = dict((status[0], status[2]) for status in ESTADO_CHOICES).get(new_status)

    #     # Management users can always change the status
    #     if user.is_management:
    #         return True

    #     # Non-management users can only move the status forward
    #     return new_status_hierarchy >= current_status_hierarchy

class LeadHistory(models.Model):
    
    form_submission = models.ForeignKey('FormSubmission', on_delete=models.CASCADE, related_name='history')
    previous_status = models.CharField(max_length=50, choices=ESTADO_CHOICES, blank=True, null=True)
    new_status = models.CharField(max_length=50, choices=ESTADO_CHOICES)
    updated_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Lead {self.form_submission.submission_id} - {self.new_status} by {self.updated_by}"

formsapp/forms.py
from django import forms
from .models import FormSubmission
from usersapp.models import CustomUser  # Import your custom user model

class FormSubmissionEditForm(forms.ModelForm):
    assigned_user = forms.ModelChoiceField(queryset=CustomUser.objects.filter(role='employee'), required=False)

    class Meta:
        model = FormSubmission
        fields = [
            'razon_social', 'nombre_y_apellido', 'telefono', 
            'estado', 'assigned_user', 'management_message'
        ]

formsapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import FormSubmission, CustomUser, ESTADO_CHOICES
from .forms import FormSubmissionEditForm
from django.utils.dateparse import parse_date

@login_required
def forms_list_view(request):
    # Start with all forms
    forms = FormSubmission.objects.all()

    # Get filter parameters from the request
    assigned_user_id = request.GET.get('assigned_user')
    estado = request.GET.get('estado')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    # Filter by assigned user if provided
    if assigned_user_id:
        forms = forms.filter(assigned_user_id=assigned_user_id)

    # Filter by estado if provided
    if estado:
        forms = forms.filter(estado=estado)

    # Filter by date range if provided
    if start_date:
        forms = forms.filter(fecha_creacion__gte=start_date)
    if end_date:
        forms = forms.filter(fecha_creacion__lte=end_date)

    # Get all users and estados for the dropdowns
    users = CustomUser.objects.all()
    estados = FormSubmission._meta.get_field('estado').choices

    return render(request, 'list_forms_submissions.html', {
        'forms': forms,
        'users': users,
        'estados': estados,
    })

@login_required
def user_leads_view(request):
    user_leads = FormSubmission.objects.filter(assigned_user=request.user)

    # Get filter values from the request
    status_filter = request.GET.get('status')
    date_from = request.GET.get('date_from')
    date_to = request.GET.get('date_to')

    # Apply status filter if provided
    if status_filter:
        user_leads = user_leads.filter(estado=status_filter)

    # Apply date filters if provided
    if date_from:
        user_leads = user_leads.filter(fecha_creacion__date__gte=parse_date(date_from))
    if date_to:
        user_leads = user_leads.filter(fecha_creacion__date__lte=parse_date(date_to))

    context = {
        'user_leads': user_leads,
        'status_filter': status_filter,
        'date_from': date_from,
        'date_to': date_to,
        'estado_choices': ESTADO_CHOICES,  # Pass status choices to the template
    }

    return render(request, 'user_leads_list.html', context)

@login_required
def form_detail_view(request, submission_id):
    form = get_object_or_404(FormSubmission, submission_id=submission_id)
    return render(request, 'form_detail.html', {'form': form})

@login_required
def user_form_detail_view(request, submission_id):
    form = get_object_or_404(FormSubmission, submission_id=submission_id)
    return render(request, 'user_form_detail.html', {'form': form})

@login_required
def form_edit_view(request, submission_id):
    form_instance = get_object_or_404(FormSubmission, submission_id=submission_id)

    if not request.user.is_management:
        return redirect('unauthorized')

    if request.method == 'POST':
        form = FormSubmissionEditForm(request.POST, instance=form_instance)
        if form.is_valid():
            form.save(commit=False)
            form_instance.save(user=request.user)  # Pass the logged-in user
            return redirect('form_detail', submission_id=submission_id)
    else:
        form = FormSubmissionEditForm(instance=form_instance)

    return render(request, 'form_edit.html', {'form': form, 'form_instance': form_instance})

@login_required
def user_form_edit_view(request, submission_id):
    form_instance = get_object_or_404(FormSubmission, submission_id=submission_id)

    if request.method == 'POST':
        form = FormSubmissionEditForm(request.POST, instance=form_instance)
        if form.is_valid():
            new_status = form.cleaned_data['estado']

            # # Check if the status change is allowed for non-management users
            # if not form_instance.is_status_change_allowed(new_status, request.user):
            #     return redirect('status_change_not_allowed')  # Redirect to an error page if not allowed

            # Save the changes with the current user
            form_instance.save(user=request.user)
            return redirect('form_detail', submission_id=submission_id)
    else:
        form = FormSubmissionEditForm(instance=form_instance)

    return render(request, 'user_form_edit.html', {'form': form, 'form_instance': form_instance})

def status_change_not_allowed_view(request):
    return render(request, 'status_change_not_allowed.html')

formsapp/templates/form_detail.html
{% extends 'base.html' %}
{% block Sidebar_menu %}
<style>
    .w3-sidebar {
        padding-top: 30px; /* Adjust this value to avoid overlap with the top bar */
    }
</style>
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bienvenido <strong>{{ request.user.username }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i> Close Menu</a>
    <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-padding w3-red"><i class="fa fa-bank fa-fw"></i>Home</a>
    <a href="{% url 'forms_list' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>Regresar al listado</a>
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i> campo5</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i> campo7</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i> campo8</a><br><br> -->
  </div>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
{% endblock %}
{% block main_page %}

<div class="w3-main">
    <h2>Detalles del formulario</h2>
    <div class="w3-container w3-card-4 w3-white w3-margin">
        <p><strong>Submission ID:</strong> {{ form.submission_id }}</p>
        <p><strong>Form ID:</strong> {{ form.form_id }}</p>
        <p><strong>Empresa:</strong> {{ form.empresa }}</p>
        <p><strong>Fecha Creacion:</strong> {{ form.fecha_creacion }}</p>
        <p><strong>Razon Social:</strong> {{ form.razon_social }}</p>
        <p><strong>Nombre y Apellido:</strong> {{ form.nombre_y_apellido }}</p>
        <p><strong>Servicio:</strong> {{ form.servicio }}</p>
        <p><strong>Mail:</strong> {{ form.mail }}</p>
        <p><strong>Telefono:</strong> {{ form.telefono }}</p>
        <p><strong>Origen:</strong> {{ form.origen }}</p>
        <p><strong>Sub-origen:</strong> {{ form.sub_origen }}</p>
        <p><strong>Mensaje:</strong> {{ form.mensaje }}</p>
        <p><strong>Avance:</strong> {{ form.avance }}</p>
        <p><strong>Estado:</strong> {{ form.estado }}</p>
        {% if request.user.is_management or request.user.is_superuser %}
            <a href="{% url 'form_edit' form.submission_id %}" class="w3-button w3-blue">Editar</a>
        {% endif %}
    </div>
</div>

{% endblock %}

formsapp/templates/form_edit.html
{% extends 'base.html' %}
{% block Sidebar_menu %}
<style>
    .w3-sidebar {
        padding-top: 30px; /* Adjust this value to avoid overlap with the top bar */
    }
</style>
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bienvenido <strong>{{ request.user.username }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i> Close Menu</a>
    <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-padding w3-red"><i class="fa fa-bank fa-fw"></i>Home</a>
    <a href="{% url 'forms_list' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>Regresar al listado</a>
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i> campo5</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i> campo7</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i> campo8</a><br><br> -->
  </div>
</nav>
<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
{% endblock %}
{% block main_page %}
<div class="w3-main">
    <h2>Editar datos del formulario</h2>
    <div class="w3-container w3-card-4 w3-white w3-margin">
        <!-- Form Start -->
        <form method="post">
            {% csrf_token %}
            
            <p>
                <label for="id_razon_social"><strong>Razon Social:</strong></label>
                {{ form.razon_social }}
            </p>

            <p>
                <label for="id_nombre_y_apellido"><strong>Nombre y Apellido:</strong></label>
                {{ form.nombre_y_apellido }}
            </p>

            <p>
                <label for="id_telefono"><strong>Telefono:</strong></label>
                {{ form.telefono }}
            </p>

            <p>
                <label for="id_estado"><strong>Estado:</strong></label>
                {{ form.estado }}
            </p>

            <p>
                <label for="id_assigned_user"><strong>Usuario asignado:</strong></label>
                {{ form.assigned_user }}
            </p>

            <p>
                <label for="id_management_message"><strong>Mensaje de gerencia:</strong></label>
                {{ form.management_message }}
            </p>

            <!-- Save Button -->
            <button type="submit" class="w3-button w3-green">Guardar</button>

            <!-- Cancel Button -->
            <a href="{% url 'form_detail' form_instance.submission_id %}" class="w3-button w3-red">Cancelar</a>
        </form>
        <!-- Form End -->
    </div>
</div>
{% endblock %}

formsapp/templates/list_forms_submissions.html
{% extends 'base.html' %}
{% block Sidebar_menu %}
<style>
.w3-sidebar {
    padding-top: 60px; /* Adjust this value to avoid overlap with the top bar */
}
</style>
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bienvenido <strong>{{ request.user.username }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <form method="GET" action="{% url 'forms_list' %}">
      <div class="w3-container">
        <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-padding w3-red"><i class="fa fa-bank fa-fw"></i>Home</a>

        <h5>Filtrar Leads</h5>

        <label for="assigned_user">Asignado a:</label>
        <select name="assigned_user" class="w3-select" id="assigned_user">
          <option value="">-- Seleccionar Usuario --</option>
          {% for user in users %}
          <option value="{{ user.id }}" {% if request.GET.assigned_user == user.id|stringformat:"s" %}selected{% endif %}>{{ user.username }}</option>
          {% endfor %}
        </select>

        <label for="estado">Estado:</label>
        <select name="estado" class="w3-select" id="estado">
          <option value="">-- Seleccionar Estado --</option>
          {% for value, label in estados %}
          <option value="{{ value }}" {% if request.GET.estado == value %}selected{% endif %}>{{ label }}</option>
          {% endfor %}
        </select>

        <label for="start_date">Desde:</label>
        <input type="date" name="start_date" class="w3-input" value="{{ request.GET.start_date }}">

        <label for="end_date">Hasta:</label>
        <input type="date" name="end_date" class="w3-input" value="{{ request.GET.end_date }}">

        <button type="submit" class="w3-button w3-block w3-green w3-margin-top">Filtrar</button>
      </div>
    </form>
  </div>
</nav>

<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
{% endblock %}

{% block main_page %}
<body class="w3-light-grey">
    <div class="w3-main">
        <h2>Formularios Completados</h2>
        <div class="table-container">
            <table class="w3-table w3-bordered w3-striped w3-hoverable">
                <thead>
                    <tr class="w3-light-grey">
                        <th>Submission ID</th>
                        <th>Razón Social</th>
                        <th>Nombre y Apellido</th>
                        <th>Servicio</th>
                        <th>Usuario asignado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form in forms %}
                    <tr data-href="{% url 'form_detail' form.submission_id %}" style="cursor:pointer;">
                        <td>{{ form.submission_id }}</td>
                        <td>{{ form.razon_social }}</td>
                        <td>{{ form.nombre_y_apellido }}</td>
                        <td>{{ form.servicio }}</td>
                        <td>{{ form.servicio }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <script>
        // JavaScript to handle the row click
        document.addEventListener("DOMContentLoaded", function() {
            var rows = document.querySelectorAll("tr[data-href]");
            rows.forEach(function(row) {
                row.addEventListener("click", function() {
                    window.location.href = this.dataset.href;
                });
            });
        });
    </script>
</body>
{% endblock %}

formsapp/templates/status_change_not_allowed.html
{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Status Change Not Allowed</title>
</head>
<body>
    <h1>Status Change Not Allowed</h1>
    <p>You do not have permission to change the status of this lead to a previous state. Please contact your manager for assistance.</p>
    <a href="{% url 'home' %}">Go Back to Home</a>
</body>

{% endblock %}

formsapp/templates/unauthorized.html
{% extends 'base.html' %}

{% block main_page %}
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
    <div class="w3-container w3-card-4 w3-white w3-margin">
        <h2>Acceso no autorizado</h2>
        <p>Usted no posee permisos para acceder a esta pagina.</p>
        <p>Si considera que esto es un error, por favor contacte con el administrador de la pagina.</p>
        <a href="{% url 'home' %}" class="w3-button w3-blue">Retornar a HOME</a>
    </div>
</div>
{% endblock %}

formsapp/templates/user_form_edit.html
{% extends 'base.html' %}

{% block Sidebar_menu %}
<style>
    .w3-sidebar {
        padding-top: 30px; /* Adjust this value to avoid overlap with the top bar */
    }
</style>
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Bienvenido <strong>{{ request.user.username }}</strong></span><br>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i></a>
      <a href="{% url 'profile' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-container">
    <h5>Dashboard</h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i> Close Menu</a>
    <a href="{% url 'home' %}" class="w3-bar-item w3-button w3-padding w3-red"><i class="fa fa-bank fa-fw"></i>Home</a>
    <a href="{% url 'user_leads' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw""></i>Regresar al listado</a>
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i> campo5</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i> campo7</a> -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i> campo8</a><br><br> -->
  </div>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
{% endblock %}

{% block main_page %}
<div class="w3-main">
    <h2>Editar formulario</h2>
    <div class="w3-container w3-card-4 w3-white w3-margin">
        <!-- Form Start -->
        <form method="post">
            {% csrf_token %}
            
            <p>
                <label for="id_razon_social"><strong>Razon Social:</strong></label>
                {{ form.razon_social }}
            </p>

            <p>
                <label for="id_nombre_y_apellido"><strong>Nombre y Apellido:</strong></label>
                {{ form.nombre_y_apellido }}
            </p>

            <p>
                <label for="id_telefono"><strong>Telefono:</strong></label>
                {{ form.telefono }}
            </p>

            <p>
                <label for="id_estado"><strong>Estado:</strong></label>
                {{ form.estado }}
            </p>

            <p>
                <label for="id_assigned_user"><strong>Usuario asignado:</strong></label>
                {{ form.assigned_user }}
            </p>

            <p>
                <label for="id_management_message"><strong>Mensaje de gerencia:</strong></label>
                {{ form.management_message }}
            </p>

            <!-- Save Button -->
            <button type="submit" class="w3-button w3-green">Guardar</button>

            <!-- Cancel Button -->
            <a href="{% url 'user_form_detail' form_instance.submission_id %}" class="w3-button w3-red">Cancelar</a>
        </form>
        <!-- Form End -->
    </div>
</div>
{% endblock %}